#!/bin/bash

# abort if a command fails
set -e

cd dynamo/eg1
python runme.py
python runme_openmp.py
cd -

cd dynamo/eg2
python runme.py
python runme_openmp.py
python runme_loop_fuse.py
cd -

cd dynamo/eg3
python ../../../src/generator.py solver_mod.x90
python ../../../src/generator.py -s ./colouring_and_omp.py -nodm solver_mod.x90
cd -

cd gocean
python runme.py
python runme_openmp.py
python runme_loop_fuse.py
cd -

cd transformations/inline
python module_inline_example.py
cd -

cd line_length
python runme.py
cd -
