!-------------------------------------------------------------------------------
! (c) The copyright relating to this work is owned jointly by the Crown, 
! Met Office and NERC 2015. 
! However, it has been created with the help of the GungHo Consortium, 
! whose members are identified at https://puma.nerc.ac.uk/trac/GungHo/wiki
!-------------------------------------------------------------------------------
!
!>@brief Meta-data for the Dynamo 0.3 point-wise kernels.
!>@details This meta-data is purely to provide psyclone with a specification
!!         of each point-wise kernel. This specification is used for
!!         correctness checking as well as to enable optimisations of
!!         invokes containing pointwise kernel calls.
!!         The actual implementation of these pointwise kernels is
!!         generated by psyclone.
module dynamo0p3_intrinsics_mod

  type, public, extends(kernel_type) :: set_field_scalar_type
     private
     type(arg_type) :: meta_args(2) = (/                                &
          arg_type(GH_FIELD,   GH_WRITE, ANY_SPACE_1),                  &
          arg_type(GH_RSCALAR, GH_READ)                                 &
          /)
     integer :: iterates_over = CELLS
   contains
     procedure, nopass :: set_field_scalar
  end type set_field_scalar_type

  type, public, extends(kernel_type) :: copy_field_type
     private
     type(arg_type) :: meta_args(2) = (/                                &
          arg_type(GH_FIELD,   GH_READ, ANY_SPACE_1),                   &
          arg_type(GH_FIELD,  GH_WRITE, ANY_SPACE_1)                    &
          /)
     integer :: iterates_over = CELLS
   contains
     procedure, nopass :: copy_field
  end type copy_field_type

end module dynamo0p3_intrinsics_mod
